name: Python Lint and Format Check

on:
  pull_request:
    paths:
      - "**/*.py"
      - "!archive/**/*.py"

jobs:
  lint:
    name: Check Python formatting and linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pylint

      # --- Ruff: formatting + linting ---
      - name: Check formatting and linting with Ruff
        run: |
          # Ruff covers Black-like formatting, linting, and import sorting
          ruff check . --output-format=github
          ruff format --check .

      # --- Pylint: deeper static analysis ---
      - name: Lint code with Pylint
        run: |
          pylint --ignore-paths=archive .
